# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 292)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -10, 391, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.firstButton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.firstButton.setObjectName("firstButton")
        self.verticalLayout.addWidget(self.firstButton)
        self.businessButton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.businessButton.setObjectName("businessButton")
        self.verticalLayout.addWidget(self.businessButton)
        self.economyButton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.economyButton.setObjectName("economyButton")
        self.verticalLayout.addWidget(self.economyButton)
        self.resultLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Wybierz rodzaj biletu"))
        self.firstButton.setText(_translate("Dialog", "Pierwsza klasa 500zł"))
        self.businessButton.setText(_translate("Dialog", "Buisiness klasa 300zł"))
        self.economyButton.setText(_translate("Dialog", "Klasa ekjonomiczna 5zł"))
